const TestimonialApi = [
    {
      id: 1,
      image: "",
      design: "Pyrénées loisirs",
      name: "Philippe MILCENT",
      offcer: "avis google",
      post: "",
      date: "2018",
      desc: "Depuis plus de 20 ans, efficace, professionnel, excellent travail et toujours au service de ses clients. Merci Monsieur Franck GALAUP.",
    },
    {
      id: 2,
      image: "../image/personne.jpg",
      design: "Midi-Pyrénées Fixation",
      name: "Cedric Sentenac",
      offcer: "avis google",
      post: "",
      date: "Le 25 mars 2022",
      desc: "Partenaire de notre société depuis bientôt 10 ans, cette société a su évoluer pour répondre à nos besoins et ceux du marché. Travail qualitatif, jamais un raté ... Quand la bonne humeur et l'amour du métier sont là, le résultat en découle.Merci à l'équipe A Vos Couleurs 👍",
    },
    {
      id: 3,
      image: "./image/slide3.png",
      design: "Intersport Collectivités labège",
      name: "Laurent Patitucci",
      offcer: "avis google",
      post: "",
      date: "Mars 2022",
      desc: "Entreprise très professionnelle , travail effectué de très bonne qualité  tant en sérigraphie qu'en broderie toute l'équipe est très sympathique et à l'écoute . Visité en mars",
    },
    {
      id: 4,
      image: "./image/slide4.png",
      design: "Commerciale",
      name: "Alexandre wormser",
      offcer: "avis google",
      post: "",
      date: "Mars 2022",
      desc: "Une équipe professionnelle à l'écoute de ses clients. Le service est top, la qualité est au rendez-vous et le sourire est toujours présent ! Je recommande !",
    },
    {
      id: 5,
      image: "./image/slide5.png",
      design: "",
      name: "Lulu N",
      offcer: "avis google",
      post: "",
      date: "Novembre 2021",
      desc: "Marquage parfait sur des gilets fluorescents. Délais respectés et bonne communication avec l'équipe professionnelle.",
    },
    // {
    //   id: 5,
    //   image: "./image/slide5.png",
    //   design: "Glassfisom",
    //   name: "Nevine Dhawan",
    //   offcer: "CEO Of Officer",
    //   post: "Android App Design",
    //   date: "Fiver - Mar 4, 2015 - Aug 30, 2021",
    //   desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris	.",
    // },
  ]
  
  export default TestimonialApi